# Используем другой образ Python, например 3.10
FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pip-audit safety

COPY . .

CMD ["bash"]
